apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autoscaler-cronjob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: discord
            - name: NAMESPACE
              value: kaellybot
            - name: STATEFULSET
              value: my-discord-bot #TODO
            - name: CONTAINER_NAME
              value: my-container-name #TODO
            - name: SHARD_ID_ENV_VAR
              value: SHARD_ID
            - name: SHARD_COUNT_ENV_VAR
              value: SHARD_COUNT
            image: ghcr.io/kaellybot/kaelly-autoscaler
            imagePullPolicy: IfNotPresent
            name: autoscaler
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: autoscaler-access
  schedule: 30 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
