apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscaler-access
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscaler-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoscaler-access
subjects:
- kind: ServiceAccount
  name: autoscaler-access